FROM kalilinux/kali-rolling:amd64

RUN apt-get update && \
    apt-get -y install --no-install-recommends sudo && \
    useradd --create-home kali && \
    echo "kali:kali" | chpasswd && \
    usermod -aG sudo kali && \
    apt-get install -y --no-install-recommends eyewitness && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/bin/eyewitness"]